// Karena tidak ada API yang menyediakan data domicile, maka saya membuat mock data
// Ini hanya untuk purpose test Rakamin saja
// GENERATED BY ChatGPT

import IndonesiaFlag from "../assets/indonesia.png";
import PalestineFlag from "../assets/palestine.png";
import PolandFlag from "../assets/poland.png";
import PortugalFlag from "../assets/portugal.png";
import PuertoRicoFlag from "../assets/puertoRico.png";

export const MOCK_DOMICILE = [
  // === Aceh ===
  { name: "Kabupaten Aceh Barat - Aceh" },
  { name: "Kabupaten Aceh Besar - Aceh" },
  { name: "Kabupaten Aceh Selatan - Aceh" },
  { name: "Kabupaten Aceh Tengah - Aceh" },
  { name: "Kabupaten Aceh Timur - Aceh" },
  { name: "Kabupaten Aceh Utara - Aceh" },
  { name: "Kota Banda Aceh - Aceh" },

  // === Sumatera Utara ===
  { name: "Kabupaten Deli Serdang - Sumatera Utara" },
  { name: "Kabupaten Langkat - Sumatera Utara" },
  { name: "Kabupaten Simalungun - Sumatera Utara" },
  { name: "Kota Medan - Sumatera Utara" },
  { name: "Kota Pematang Siantar - Sumatera Utara" },
  { name: "Kota Binjai - Sumatera Utara" },

  // === Sumatera Barat ===
  { name: "Kabupaten Agam - Sumatera Barat" },
  { name: "Kabupaten Lima Puluh Kota - Sumatera Barat" },
  { name: "Kota Padang - Sumatera Barat" },
  { name: "Kota Bukittinggi - Sumatera Barat" },

  // === Riau ===
  { name: "Kabupaten Kampar - Riau" },
  { name: "Kabupaten Rokan Hulu - Riau" },
  { name: "Kota Pekanbaru - Riau" },

  // === Jambi ===
  { name: "Kabupaten Batanghari - Jambi" },
  { name: "Kabupaten Tebo - Jambi" },
  { name: "Kota Jambi - Jambi" },

  // === Sumatera Selatan ===
  { name: "Kabupaten Musi Banyuasin - Sumatera Selatan" },
  { name: "Kabupaten Ogan Komering Ilir - Sumatera Selatan" },
  { name: "Kota Palembang - Sumatera Selatan" },

  // === Bengkulu ===
  { name: "Kabupaten Bengkulu Selatan - Bengkulu" },
  { name: "Kabupaten Rejang Lebong - Bengkulu" },
  { name: "Kota Bengkulu - Bengkulu" },

  // === Lampung ===
  { name: "Kabupaten Lampung Selatan - Lampung" },
  { name: "Kabupaten Lampung Tengah - Lampung" },
  { name: "Kota Bandar Lampung - Lampung" },

  // === DKI Jakarta ===
  { name: "Kota Jakarta Pusat - DKI Jakarta" },
  { name: "Kota Jakarta Barat - DKI Jakarta" },
  { name: "Kota Jakarta Timur - DKI Jakarta" },
  { name: "Kota Jakarta Selatan - DKI Jakarta" },
  { name: "Kota Jakarta Utara - DKI Jakarta" },

  // === Jawa Barat ===
  { name: "Kabupaten Bandung - Jawa Barat" },
  { name: "Kabupaten Sumedang - Jawa Barat" },
  { name: "Kabupaten Bogor - Jawa Barat" },
  { name: "Kota Bandung - Jawa Barat" },
  { name: "Kota Bekasi - Jawa Barat" },
  { name: "Kota Depok - Jawa Barat" },

  // === Jawa Tengah ===
  { name: "Kabupaten Semarang - Jawa Tengah" },
  { name: "Kabupaten Boyolali - Jawa Tengah" },
  { name: "Kabupaten Banyumas - Jawa Tengah" },
  { name: "Kota Semarang - Jawa Tengah" },
  { name: "Kota Surakarta - Jawa Tengah" },
  { name: "Kota Magelang - Jawa Tengah" },

  // === DI Yogyakarta ===
  { name: "Kabupaten Sleman - DI Yogyakarta" },
  { name: "Kabupaten Bantul - DI Yogyakarta" },
  { name: "Kota Yogyakarta - DI Yogyakarta" },

  // === Jawa Timur ===
  { name: "Kabupaten Malang - Jawa Timur" },
  { name: "Kabupaten Sidoarjo - Jawa Timur" },
  { name: "Kabupaten Banyuwangi - Jawa Timur" },
  { name: "Kota Surabaya - Jawa Timur" },
  { name: "Kota Malang - Jawa Timur" },

  // === Bali ===
  { name: "Kabupaten Badung - Bali" },
  { name: "Kabupaten Gianyar - Bali" },
  { name: "Kota Denpasar - Bali" },

  // === Nusa Tenggara Barat ===
  { name: "Kabupaten Lombok Barat - Nusa Tenggara Barat" },
  { name: "Kabupaten Lombok Timur - Nusa Tenggara Barat" },
  { name: "Kota Mataram - Nusa Tenggara Barat" },

  // === Kalimantan Barat ===
  { name: "Kabupaten Ketapang - Kalimantan Barat" },
  { name: "Kabupaten Sanggau - Kalimantan Barat" },
  { name: "Kota Pontianak - Kalimantan Barat" },

  // === Kalimantan Timur ===
  { name: "Kabupaten Kutai Kartanegara - Kalimantan Timur" },
  { name: "Kabupaten Berau - Kalimantan Timur" },
  { name: "Kota Samarinda - Kalimantan Timur" },
  { name: "Kota Balikpapan - Kalimantan Timur" },

  // === Sulawesi Selatan ===
  { name: "Kabupaten Gowa - Sulawesi Selatan" },
  { name: "Kabupaten Bone - Sulawesi Selatan" },
  { name: "Kota Makassar - Sulawesi Selatan" },

  // === Sulawesi Tengah ===
  { name: "Kabupaten Donggala - Sulawesi Tengah" },
  { name: "Kabupaten Parigi Moutong - Sulawesi Tengah" },
  { name: "Kota Palu - Sulawesi Tengah" },

  // === Sulawesi Utara ===
  { name: "Kabupaten Minahasa - Sulawesi Utara" },
  { name: "Kabupaten Bolaang Mongondow - Sulawesi Utara" },
  { name: "Kota Manado - Sulawesi Utara" },

  // === Maluku ===
  { name: "Kabupaten Maluku Tengah - Maluku" },
  { name: "Kabupaten Seram Bagian Barat - Maluku" },
  { name: "Kota Ambon - Maluku" },

  // === Papua ===
  { name: "Kabupaten Jayapura - Papua" },
  { name: "Kabupaten Mimika - Papua" },
  { name: "Kota Jayapura - Papua" },
];

export const MOCK_COUNTRIES = [
  { name: "Indonesia", code: "+62", flag: IndonesiaFlag },
  { name: "Palestine", code: "+970", flag: PalestineFlag },
  { name: "Poland", code: "+48", flag: PolandFlag },
  { name: "Portugal", code: "+351", flag: PortugalFlag },
  { name: "Puerto Rico", code: "+1", flag: PuertoRicoFlag },
];
